"""
Tests for the georeader.read module and georeader.dataarray module functions.

These tests verify the core reading functionality including:
- Converting xarray coordinates to transform
- Reading data from windows
- Reading data from bounds
- Reprojecting data to same and different resolutions

Uses a temporary GeoTiff test file created via the test_raster_path fixture.
The test file has: 15 bands, height=200, width=250, CRS=EPSG:32738, resolution=10.0m
"""

from georeader import read, rasterio_reader, dataarray
from georeader.window_utils import window_bounds
import rasterio
import rasterio.windows
import numpy as np
import pytest
import math
import itertools

# Define windows for testing - based on the test image dimensions (height=200, width=250)
# Normal window within bounds
WINDOW_NORMAL = rasterio.windows.Window(col_off=50, row_off=50, width=64, height=64)

# Windows that go out of bounds (for boundless read testing)
WINDOW_OUT_1 = rasterio.windows.Window(col_off=-10, row_off=-15, width=64, height=64)  # Out top-left
WINDOW_OUT_2 = rasterio.windows.Window(col_off=-10, row_off=180, width=64, height=64)  # Out bottom-left
WINDOW_OUT_3 = rasterio.windows.Window(col_off=230, row_off=20, width=64, height=64)  # Out right
WINDOW_OUT_4 = rasterio.windows.Window(col_off=230, row_off=180, width=64, height=64)  # Out bottom-right
WINDOW_OUT_5 = rasterio.windows.Window(col_off=200, row_off=150, width=64, height=64)  # Partial out bottom-right

# Border cases - windows touching image boundaries
WINDOW_BORDER_1 = rasterio.windows.Window(col_off=186, row_off=20, width=64, height=64)  # Border right
WINDOW_BORDER_2 = rasterio.windows.Window(col_off=50, row_off=136, width=64, height=64)  # Border bottom

# Fully out of bounds windows
WINDOW_FULLY_OUT_1 = rasterio.windows.Window(col_off=-70, row_off=34, width=64, height=64)  # Fully out left
WINDOW_FULLY_OUT_2 = rasterio.windows.Window(col_off=-1, row_off=-70, width=14, height=64)  # Fully out top


def test_transform_bounds(test_raster_path):
    """
    Test that the transform computed from xarray coordinates matches rasterio's transform.

    This verifies that dataarray.coords_to_transform correctly reconstructs the geotransform
    from the x and y coordinate arrays that would be generated by rasterio when reading a file.
    """
    with rasterio.open(test_raster_path) as src:
        exp_transform = src.transform
        # Create coordinates from the transform and shape (as xarray would do)
        coords = dataarray.getcoords_from_transform_shape(exp_transform, (src.height, src.width))

    # Now verify we can recover the transform from these coordinates
    import xarray as xr
    coords_obj = xr.Coordinates(coords)
    transform = dataarray.coords_to_transform(coords_obj)

    assert transform == exp_transform, f"Different transform {transform} expected: {exp_transform}"


def get_test_windows(test_raster_path):
    """Return list of test windows paired with the test file path."""
    return [
        (test_raster_path, WINDOW_NORMAL),
        (test_raster_path, WINDOW_OUT_1),
        (test_raster_path, WINDOW_OUT_2),
        (test_raster_path, WINDOW_OUT_3),
        (test_raster_path, WINDOW_OUT_4),
        (test_raster_path, WINDOW_OUT_5),
        (test_raster_path, WINDOW_BORDER_1),
        (test_raster_path, WINDOW_BORDER_2),
        (test_raster_path, WINDOW_FULLY_OUT_1),
        (test_raster_path, WINDOW_FULLY_OUT_2),
    ]


# List of just windows for parametrized tests
TEST_WINDOWS = [
    WINDOW_NORMAL,
    WINDOW_OUT_1,
    WINDOW_OUT_2,
    WINDOW_OUT_3,
    WINDOW_OUT_4,
    WINDOW_OUT_5,
    WINDOW_BORDER_1,
    WINDOW_BORDER_2,
    WINDOW_FULLY_OUT_1,
    WINDOW_FULLY_OUT_2,
]

# Combine windows with trigger_load options
TRIGGER_LOAD_OPTIONS = [True, False]
TEST_COMBINATIONS = list(itertools.product(TEST_WINDOWS, TRIGGER_LOAD_OPTIONS))


@pytest.mark.parametrize("window,trigger_load", TEST_COMBINATIONS)
def test_read_window(test_raster_path, window, trigger_load):
    """
    Test reading data from a window using read.read_from_window.

    This test verifies that:
    1. The read_from_window function correctly slices data from a raster
    2. The output shape matches the window dimensions
    3. The bounds and transform of the output match expected values
    4. The actual data values match what rasterio would read directly

    Args:
        test_raster_path: Path to the test raster file (fixture)
        window: Window to read from
        trigger_load: Whether to trigger loading data into memory
    """
    data_array = rasterio_reader.RasterioReader(test_raster_path)

    chip_out = read.read_from_window(data_array, window, trigger_load=trigger_load)

    # Skip fully out-of-bounds windows when not boundless
    if chip_out is None:
        return

    # Check that the output has the correct shape
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height, \
        f"Different height found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    assert named_shape["x"] == window.width, \
        f"Different width found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"

    # Check the same data is read with rasterio
    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        expected_bounds = rasterio.windows.bounds(window, src.transform)

    # Verify bounds and transform
    assert chip_out.bounds == expected_bounds, \
        f"Different bounds found: {chip_out.bounds} expected: {expected_bounds}"
    assert chip_out.transform == expected_transform, \
        f"Different transform found: {chip_out.transform} expected: {expected_transform}"

    # Verify the actual data values match
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


@pytest.mark.parametrize("window,trigger_load", TEST_COMBINATIONS)
def test_read_bounds(test_raster_path, window, trigger_load):
    """
    Test reading data from bounds using read.read_from_bounds.

    This test verifies that:
    1. The read_from_bounds function correctly reads data for a given bounding box
    2. The output shape matches the expected dimensions
    3. The bounds and transform of the output are correct
    4. The actual data values match what rasterio would read directly

    Args:
        test_raster_path: Path to the test raster file (fixture)
        window: Window to derive bounds from
        trigger_load: Whether to trigger loading data into memory
    """
    data_array = rasterio_reader.RasterioReader(test_raster_path)

    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        crs_bounds = src.crs

    chip_out = read.read_from_bounds(data_array, bounds_read, crs_bounds=crs_bounds, trigger_load=trigger_load)

    # Skip fully out-of-bounds windows when not boundless
    if chip_out is None:
        return

    # Check that the output has the correct shape
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height, \
        f"Different height found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    assert named_shape["x"] == window.width, \
        f"Different width found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"

    # Verify bounds and transform
    assert chip_out.bounds == bounds_read, \
        f"Different bounds found: {chip_out.bounds} expected: {bounds_read}"
    assert chip_out.transform == expected_transform, \
        f"Different transform found: {chip_out.transform} expected: {expected_transform}"

    # Verify the actual data values match
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_reproject_same(test_raster_path, window):
    """
    Test reprojecting data to the same CRS and resolution.

    This test verifies that when reprojecting data to the same CRS with the same
    resolution, we get back equivalent data. This is essentially a round-trip test
    for the read_reproject function.

    Args:
        test_raster_path: Path to the test raster file (fixture)
        window: Window to derive bounds from
    """
    data_array = rasterio_reader.RasterioReader(test_raster_path)

    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        crs_bounds = src.crs

    chip_out = read.read_reproject(
        data_array, bounds=bounds_read, dst_crs=crs_bounds,
        resolution_dst_crs=(abs(expected_transform.a), abs(expected_transform.e))
    )

    # Skip fully out-of-bounds windows
    if chip_out is None:
        return

    # Check that the output has the correct shape
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height, \
        f"Different height found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    assert named_shape["x"] == window.width, \
        f"Different width found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"

    # Verify bounds and transform
    assert chip_out.bounds == bounds_read, \
        f"Different bounds found: {chip_out.bounds} expected: {bounds_read}"
    assert chip_out.transform == expected_transform, \
        f"Different transform found: {chip_out.transform} expected: {expected_transform}"

    # Verify the actual data values match (allowing for small differences due to reprojection)
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


RESOLUTION_TEST = (5.0, 5.0)  # Test with 5m resolution (half of original 10m)


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_reproject_other_res(test_raster_path, window):
    """
    Test reprojecting data to a different resolution.

    This test verifies that read_reproject correctly handles resolution changes.
    When changing from 10m to 5m resolution, the output should have 2x the number
    of pixels in each dimension.

    Args:
        test_raster_path: Path to the test raster file (fixture)
        window: Window to derive bounds from
    """
    data_array = rasterio_reader.RasterioReader(test_raster_path)

    with rasterio.open(test_raster_path) as src:
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        factor_diff_shape = np.array(src.res) / np.array(RESOLUTION_TEST)
        crs_bounds = src.crs

    chip_out = read.read_reproject(
        data_array, bounds=bounds_read, dst_crs=crs_bounds,
        resolution_dst_crs=RESOLUTION_TEST
    )

    # Skip fully out-of-bounds windows
    if chip_out is None:
        return

    # Check that the output has the correct shape (scaled by resolution factor)
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == int(window.height * factor_diff_shape[1]), \
        f"Different height found: {named_shape['y']} expected {int(window.height * factor_diff_shape[1])}"
    assert named_shape["x"] == int(window.width * factor_diff_shape[0]), \
        f"Different width found: {named_shape['x']} expected {int(window.width * factor_diff_shape[0])}"

    # Verify bounds remain the same
    assert chip_out.bounds == bounds_read, \
        f"Different bounds found: {chip_out.bounds} expected: {bounds_read}"

    # Verify the transform has the expected resolution
    resolution_signed = (
        math.copysign(RESOLUTION_TEST[0], expected_transform.a),
        math.copysign(RESOLUTION_TEST[1], expected_transform.e)
    )

    expected_transform_new_res = (
        rasterio.Affine.translation(expected_transform.c, expected_transform.f) *
        rasterio.Affine.scale(*resolution_signed)
    )

    assert chip_out.transform == expected_transform_new_res, \
        f"Different transform found: {chip_out.transform} expected: {expected_transform_new_res}"


def test_read_after_set_window(test_raster_path):
    """
    Test that reading from bounds works correctly with and without a window_focus set.

    This test verifies that the read_from_bounds function produces the same results
    regardless of whether a window_focus is set on the reader, ensuring consistent
    behavior when using different reading patterns.
    """
    # Create a window that is within the image bounds (height=200, width=250)
    window_focus = rasterio.windows.Window(col_off=50, row_off=50, width=100, height=100)

    rst1 = rasterio_reader.RasterioReader(test_raster_path)
    rst2 = rasterio_reader.RasterioReader(test_raster_path, window_focus=window_focus)

    # Get bounds within the window_focus area using the raster's CRS
    with rasterio.open(test_raster_path) as src:
        # Compute bounds for a small area within window_focus
        inner_window = rasterio.windows.Window(col_off=75, row_off=75, width=50, height=50)
        bounds_read = rasterio.windows.bounds(inner_window, src.transform)
        crs_bounds = src.crs

    data1 = read.read_from_bounds(rst1, bounds_read, crs_bounds=crs_bounds)
    data2 = read.read_from_bounds(rst2, bounds_read, crs_bounds=crs_bounds)

    assert data1.bounds == data2.bounds, \
        f"Different bounds found: {data1.bounds} expected: {data2.bounds}"
    assert data1.transform == data2.transform, \
        f"Different transform found: {data1.transform} expected: {data2.transform}"

    assert np.allclose(data1.values, data2.values), "Content of the array is different"
