"""
Tests for the georeader.read module and georeader.dataarray module functions.

These tests verify the core reading functionality including:
- Converting xarray coordinates to transform
- Reading data from windows
- Reading data from bounds
- Reprojecting data to same and different resolutions

Uses a temporary GeoTiff test file created via the test_raster_path fixture.
The test file has: 15 bands, height=200, width=250, CRS=EPSG:32738, resolution=10.0m
"""

import asyncio
import itertools
import math
import os

import numpy as np
import pytest
import rasterio
import rasterio.warp
import rasterio.windows
from shapely.geometry import box

from georeader import dataarray, rasterio_reader, read
from georeader.geotensor import GeoTensor

# Define windows for testing - based on the test image dimensions (height=200, width=250)
# Normal window within bounds
WINDOW_NORMAL = rasterio.windows.Window(col_off=50, row_off=50, width=64, height=64)

# Windows that go out of bounds (for boundless read testing)
WINDOW_OUT_1 = rasterio.windows.Window(col_off=-10, row_off=-15, width=64, height=64)  # Out top-left
WINDOW_OUT_2 = rasterio.windows.Window(col_off=-10, row_off=180, width=64, height=64)  # Out bottom-left
WINDOW_OUT_3 = rasterio.windows.Window(col_off=230, row_off=20, width=64, height=64)  # Out right
WINDOW_OUT_4 = rasterio.windows.Window(col_off=230, row_off=180, width=64, height=64)  # Out bottom-right
WINDOW_OUT_5 = rasterio.windows.Window(col_off=200, row_off=150, width=64, height=64)  # Partial out bottom-right

# Border cases - windows touching image boundaries
WINDOW_BORDER_1 = rasterio.windows.Window(col_off=186, row_off=20, width=64, height=64)  # Border right
WINDOW_BORDER_2 = rasterio.windows.Window(col_off=50, row_off=136, width=64, height=64)  # Border bottom

# Fully out of bounds windows
WINDOW_FULLY_OUT_1 = rasterio.windows.Window(col_off=-70, row_off=34, width=64, height=64)  # Fully out left
WINDOW_FULLY_OUT_2 = rasterio.windows.Window(col_off=-1, row_off=-70, width=14, height=64)  # Fully out top


def test_transform_bounds(test_raster_path):
    """
    Test that the transform computed from xarray coordinates matches rasterio's transform.

    This verifies that dataarray.coords_to_transform correctly reconstructs the geotransform
    from the x and y coordinate arrays that would be generated by rasterio when reading a file.
    """
    with rasterio.open(test_raster_path) as src:
        exp_transform = src.transform
        # Create coordinates from the transform and shape (as xarray would do)
        coords = dataarray.getcoords_from_transform_shape(exp_transform, (src.height, src.width))

    # Now verify we can recover the transform from these coordinates
    import xarray as xr

    coords_obj = xr.Coordinates(coords)
    transform = dataarray.coords_to_transform(coords_obj)

    assert transform == exp_transform, f"Different transform {transform} expected: {exp_transform}"


def get_test_windows(test_raster_path):
    """Return list of test windows paired with the test file path."""
    return [
        (test_raster_path, WINDOW_NORMAL),
        (test_raster_path, WINDOW_OUT_1),
        (test_raster_path, WINDOW_OUT_2),
        (test_raster_path, WINDOW_OUT_3),
        (test_raster_path, WINDOW_OUT_4),
        (test_raster_path, WINDOW_OUT_5),
        (test_raster_path, WINDOW_BORDER_1),
        (test_raster_path, WINDOW_BORDER_2),
        (test_raster_path, WINDOW_FULLY_OUT_1),
        (test_raster_path, WINDOW_FULLY_OUT_2),
    ]


# List of just windows for parametrized tests
TEST_WINDOWS = [
    WINDOW_NORMAL,
    WINDOW_OUT_1,
    WINDOW_OUT_2,
    WINDOW_OUT_3,
    WINDOW_OUT_4,
    WINDOW_OUT_5,
    WINDOW_BORDER_1,
    WINDOW_BORDER_2,
    WINDOW_FULLY_OUT_1,
    WINDOW_FULLY_OUT_2,
]

# Combine windows with trigger_load options
TRIGGER_LOAD_OPTIONS = [True, False]
TEST_COMBINATIONS = list(itertools.product(TEST_WINDOWS, TRIGGER_LOAD_OPTIONS))


# =============================================================================
# Parametrized reader fixture — runs each `read.*` test against both
# RasterioReader (sync) and AsyncGeoTIFFReader (async). Mirrors the
# reviewer's request to avoid copy-paste and exercise the read module's
# polymorphism over the two reader types.
# =============================================================================

def _materialize_sync(view_or_tensor):
    """Convert a lazy reader view (or pre-built GeoTensor) into a GeoTensor."""
    if view_or_tensor is None or isinstance(view_or_tensor, GeoTensor):
        return view_or_tensor
    return view_or_tensor.load()


def _materialize_async(view_or_tensor):
    """Async sibling of _materialize_sync — drives ``view.load()`` via asyncio.run."""
    if view_or_tensor is None or isinstance(view_or_tensor, GeoTensor):
        return view_or_tensor
    return asyncio.run(view_or_tensor.load())


@pytest.fixture(params=["sync", "async"])
def reader_and_materialize(request, test_raster_path):
    """Yield ``(reader, materialize)`` for each reader backend.

    The ``materialize`` helper turns whatever ``read.*`` returns
    (lazy reader view, pre-built GeoTensor, or None for the
    no-intersection-boundless-False branch) into a GeoTensor that the
    test can assert against — handling sync ``.load()`` or async
    ``await view.load()`` transparently.
    """
    if request.param == "sync":
        reader = rasterio_reader.RasterioReader(test_raster_path)
        yield reader, _materialize_sync
        return

    # async path — skip cleanly if the optional extra isn't installed.
    pytest.importorskip("async_geotiff")
    obstore = pytest.importorskip("obstore")
    from georeader.async_geotiff_reader import AsyncGeoTIFFReader

    store = obstore.store.LocalStore(prefix=os.path.dirname(test_raster_path))
    fname = os.path.basename(test_raster_path)
    reader = asyncio.run(AsyncGeoTIFFReader.open(fname, store=store))
    yield reader, _materialize_async


def _as_geotensor_for_reproject(reader, materialize):
    """Coerce a reader into a GeoTensor so ``read.read_reproject`` can consume it.

    ``read.read_reproject`` materialises source data internally via a
    sync ``trigger_load=True`` ([read.py:1547](../georeader/read.py#L1547)
    and [read.py:1605-1608](../georeader/read.py#L1605-L1608)) — fine
    for sync readers, returns a coroutine for async. The
    ``isinstance(data_in, GeoTensor)`` short-circuit at
    [read.py:1605](../georeader/read.py#L1605) is the seam: if the
    input is already in memory, the sync-load path is skipped.

    So the canonical async pattern is: pre-load (1 ``await``) then
    pass the GeoTensor. No ``aread_reproject`` needed — same function
    works for both readers.
    """
    return materialize(reader.read_from_window(rasterio.windows.Window(
        col_off=0, row_off=0, width=reader.shape[-1], height=reader.shape[-2],
    )))


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_window(reader_and_materialize, test_raster_path, window):
    """
    Test reading data from a window using read.read_from_window.

    Runs against both RasterioReader (sync) and AsyncGeoTIFFReader
    (async) via the ``reader_and_materialize`` fixture.

    Verifies:
    1. read_from_window correctly slices data from a raster
    2. Output shape matches the window dimensions
    3. Bounds and transform of the output match expected values
    4. Actual data values match what rasterio would read directly
    """
    reader, materialize = reader_and_materialize

    result = read.read_from_window(reader, window)
    chip_out = materialize(result)

    # Skip fully out-of-bounds windows when not boundless
    if chip_out is None:
        return

    # Check that the output has the correct shape
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height, (
        f"Different height found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    )
    assert named_shape["x"] == window.width, (
        f"Different width found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    )

    # Check the same data is read with rasterio
    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        expected_bounds = rasterio.windows.bounds(window, src.transform)

    # Verify bounds and transform
    assert chip_out.bounds == expected_bounds, f"Different bounds found: {chip_out.bounds} expected: {expected_bounds}"
    assert chip_out.transform == expected_transform, (
        f"Different transform found: {chip_out.transform} expected: {expected_transform}"
    )

    # Verify the actual data values match
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


@pytest.mark.parametrize("window,trigger_load", TEST_COMBINATIONS)
def test_read_window_sync_trigger_load(test_raster_path, window, trigger_load):
    """Sync-only smoke test for ``trigger_load`` on ``read.read_from_window``.

    The async path has no equivalent (``trigger_load`` would try to call
    ``view.load()`` synchronously — for an async view that returns a
    coroutine, not a GeoTensor). Keeping this here so the
    ``trigger_load`` branch of :func:`read.read_from_window` stays
    covered for the sync reader.
    """
    rst = rasterio_reader.RasterioReader(test_raster_path)

    chip_out = read.read_from_window(rst, window, trigger_load=trigger_load)
    if chip_out is None:
        return

    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)

    assert np.allclose(chip_out_expected, chip_out.values)


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_bounds(reader_and_materialize, test_raster_path, window):
    """
    Test reading data from bounds using read.read_from_bounds.

    Runs against both reader backends via ``reader_and_materialize``.
    """
    reader, materialize = reader_and_materialize

    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        crs_bounds = src.crs

    result = read.read_from_bounds(reader, bounds_read, crs_bounds=crs_bounds)
    chip_out = materialize(result)

    if chip_out is None:
        return

    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height, (
        f"Different height found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    )
    assert named_shape["x"] == window.width, (
        f"Different width found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    )
    assert chip_out.bounds == bounds_read, f"Different bounds found: {chip_out.bounds} expected: {bounds_read}"
    assert chip_out.transform == expected_transform, (
        f"Different transform found: {chip_out.transform} expected: {expected_transform}"
    )
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_polygon(reader_and_materialize, test_raster_path, window):
    """Test reading data from a polygon (box) via read.read_from_polygon.

    Uses the window's geographic bounds to build a rectangular polygon
    and verifies the returned chip matches a direct rasterio read of
    the same window.
    """
    reader, materialize = reader_and_materialize

    with rasterio.open(test_raster_path) as src:
        bounds_read = rasterio.windows.bounds(window, src.transform)
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        crs_bounds = src.crs

    polygon = box(*bounds_read)
    result = read.read_from_polygon(reader, polygon, crs_polygon=crs_bounds)
    chip_out = materialize(result)

    if chip_out is None:
        return

    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height
    assert named_shape["x"] == window.width
    assert chip_out.bounds == bounds_read
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


# In-bounds windows only — cross-CRS reprojection of out-of-bounds windows is
# meaningless (bounds wrap or land in invalid lat/lon) and gives noisy failures
# that don't tell us anything about the read.* polymorphism we're checking.
IN_BOUNDS_WINDOWS = [WINDOW_NORMAL, WINDOW_BORDER_1, WINDOW_BORDER_2]


@pytest.mark.parametrize("window", IN_BOUNDS_WINDOWS)
def test_read_bounds_cross_crs(reader_and_materialize, test_raster_path, window):
    """Coverage gap #9 — read.read_from_bounds with bounds in a different CRS.

    The reviewer's wording "shall work with this reader as input
    regardless of the crs passed because it reprojects the bounds not
    the data" is exactly this path. Bounds reprojection happens in
    :func:`window_utils.window_from_bounds` before any I/O — the
    reader doesn't see the WGS84 bounds, only the resolved native-CRS
    window.
    """
    reader, materialize = reader_and_materialize

    with rasterio.open(test_raster_path) as src:
        utm_bounds = rasterio.windows.bounds(window, src.transform)
        src_crs = src.crs
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)

    del chip_out_expected  # bounds CRS round-trip shifts the window — byte parity isn't the point here
    wgs_bounds = rasterio.warp.transform_bounds(src_crs, "EPSG:4326", *utm_bounds)
    chip_out = materialize(read.read_from_bounds(reader, wgs_bounds, crs_bounds="EPSG:4326"))

    if chip_out is None:
        return
    # CRS round-trip introduces a small bounds wiggle; allow ±2 pixels in shape.
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert abs(named_shape["y"] - window.height) <= 2
    assert abs(named_shape["x"] - window.width) <= 2
    # The reader's data stays in its native CRS — bounds are reprojected
    # but data is not (the point of read.read_from_bounds with crs_bounds).
    assert str(chip_out.crs) == str(src_crs)


@pytest.mark.parametrize("window", IN_BOUNDS_WINDOWS)
def test_read_polygon_cross_crs(reader_and_materialize, test_raster_path, window):
    """Coverage gap #11 — read.read_from_polygon with polygon in a different CRS.

    Same shape as :func:`test_read_bounds_cross_crs` but via the polygon path.
    """
    reader, materialize = reader_and_materialize

    with rasterio.open(test_raster_path) as src:
        utm_bounds = rasterio.windows.bounds(window, src.transform)
        src_crs = src.crs

    wgs_bounds = rasterio.warp.transform_bounds(src_crs, "EPSG:4326", *utm_bounds)
    poly = box(*wgs_bounds)
    chip_out = materialize(read.read_from_polygon(reader, poly, crs_polygon="EPSG:4326"))

    if chip_out is None:
        return
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert abs(named_shape["y"] - window.height) <= 2
    assert abs(named_shape["x"] - window.width) <= 2
    assert str(chip_out.crs) == str(src_crs)


@pytest.mark.parametrize("pad", [(4, 4), (16, 16), (0, 8)])
def test_read_bounds_pad_add(reader_and_materialize, test_raster_path, pad):
    """Coverage gap #10 — read.read_from_bounds with ``pad_add``.

    ``pad_add`` is documented for CNN inference / receptive field
    context. Verify the output is larger than the unpadded read by
    exactly ``2 * pad`` in each axis (pad is added on both sides).
    """
    reader, materialize = reader_and_materialize

    with rasterio.open(test_raster_path) as src:
        bounds_read = rasterio.windows.bounds(WINDOW_NORMAL, src.transform)
        crs_bounds = src.crs

    unpadded = materialize(read.read_from_bounds(reader, bounds_read, crs_bounds=crs_bounds))
    padded = materialize(read.read_from_bounds(reader, bounds_read, crs_bounds=crs_bounds, pad_add=pad))

    assert unpadded is not None and padded is not None
    u_shape = dict(zip(unpadded.dims, unpadded.shape))
    p_shape = dict(zip(padded.dims, padded.shape))
    assert p_shape["y"] == u_shape["y"] + 2 * pad[0]
    assert p_shape["x"] == u_shape["x"] + 2 * pad[1]


def test_read_window_return_only_data_sync(test_raster_path):
    """Coverage gap #8 — ``return_only_data=True`` returns a bare numpy array.

    Sync-only: this branch calls ``data_sel.values`` on the reader's
    view ([read.py:582-583](../georeader/read.py#L582-L583)). For an
    async reader's view, ``.values`` would need to materialise via
    ``await load()`` — which the sync read module can't do. The
    documented workaround for async users is to call ``await
    view.load()`` and then ``.values`` on the resulting GeoTensor.
    """
    rst = rasterio_reader.RasterioReader(test_raster_path)
    arr = read.read_from_window(rst, WINDOW_NORMAL, return_only_data=True)
    assert isinstance(arr, np.ndarray)
    assert arr.shape[-2:] == (WINDOW_NORMAL.height, WINDOW_NORMAL.width)


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_center_coords(reader_and_materialize, test_raster_path, window):
    """Test read.read_from_center_coords against both reader backends.

    Computes the geographic center of the window and reads back a chip
    of the same (height, width); compares to a direct rasterio read.
    """
    reader, materialize = reader_and_materialize

    with rasterio.open(test_raster_path) as src:
        bounds_read = rasterio.windows.bounds(window, src.transform)
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        crs_bounds = src.crs

    center = ((bounds_read[0] + bounds_read[2]) / 2.0, (bounds_read[1] + bounds_read[3]) / 2.0)
    shape = (window.height, window.width)

    result = read.read_from_center_coords(
        reader, center_coords=center, shape=shape, crs_center_coords=crs_bounds,
    )
    chip_out = materialize(result)

    if chip_out is None:
        return

    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height
    assert named_shape["x"] == window.width
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


def test_read_from_tile(reader_and_materialize, test_raster_path):
    """Test read.read_from_tile against both reader backends.

    Picks an XYZ tile whose footprint intersects the test raster (the
    raster is in EPSG:32738 South-East Africa; pick a low-zoom tile
    covering that area) and verifies that the returned chip has the
    expected web-mercator shape and CRS.
    """
    reader, materialize = reader_and_materialize

    # Compute a Z/X/Y tile covering the raster's geographic center.
    with rasterio.open(test_raster_path) as src:
        center_x = (src.bounds.left + src.bounds.right) / 2.0
        center_y = (src.bounds.bottom + src.bounds.top) / 2.0
        src_crs = src.crs

    lon, lat = rasterio.warp.transform(src_crs, "EPSG:4326", [center_x], [center_y])
    lon, lat = lon[0], lat[0]

    z = 12
    n = 2 ** z
    xtile = int((lon + 180.0) / 360.0 * n)
    ytile = int((1.0 - math.log(math.tan(math.radians(lat)) + 1.0 / math.cos(math.radians(lat))) / math.pi) / 2.0 * n)

    result = read.read_from_tile(reader, x=xtile, y=ytile, z=z)
    chip_out = materialize(result)

    if chip_out is None:
        return

    # Web-mercator tile reads return EPSG:3857 by default.
    assert str(chip_out.crs) == "EPSG:3857" or "3857" in str(chip_out.crs)
    # Tile shape is non-degenerate.
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] > 0
    assert named_shape["x"] > 0


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_reproject_like(reader_and_materialize, test_raster_path, window):
    """Test read.read_reproject_like — reproject reader to match a GeoTensor template.

    Constructs an in-memory GeoTensor whose bounds correspond to the
    test window in the reader's native CRS. Asks the reader to
    reproject onto that template and verifies shape, bounds, and (loose)
    value equality with a direct rasterio read of the same window.

    Async readers are coerced to a GeoTensor first via
    :func:`_as_geotensor_for_reproject`; ``read.read_reproject_like``
    then takes the in-memory short-circuit at
    [read.py:1605](../georeader/read.py#L1605).
    """
    reader, materialize = reader_and_materialize
    reader = _as_geotensor_for_reproject(reader, materialize)

    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        crs_bounds = src.crs

    template = GeoTensor(
        np.zeros((1, window.height, window.width), dtype=np.float32),
        transform=expected_transform,
        crs=crs_bounds,
    )

    chip_out = read.read_reproject_like(reader, template)

    if chip_out is None:
        return

    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height
    assert named_shape["x"] == window.width
    assert chip_out.bounds == bounds_read, f"Different bounds: {chip_out.bounds} vs {bounds_read}"
    # Reprojection at same CRS / resolution is a pixel-aligned copy → exact match.
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_reproject_same(reader_and_materialize, test_raster_path, window):
    """
    Test reprojecting data to the same CRS and resolution.

    Round-trip test for read_reproject — reprojecting to the source's
    own CRS at the same resolution should return pixel-aligned data.

    For async readers, pre-load the source into a GeoTensor before
    calling read_reproject. ``read.read_reproject`` short-circuits the
    sync materialisation when ``isinstance(data_in, GeoTensor)`` at
    [read.py:1605](../georeader/read.py#L1605), so no ``aread_reproject``
    sibling is needed — the existing function handles both readers via
    this pattern.
    """
    reader, materialize = reader_and_materialize
    reader = _as_geotensor_for_reproject(reader, materialize)

    with rasterio.open(test_raster_path) as src:
        chip_out_expected = src.read(window=window, boundless=True, fill_value=0)
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        crs_bounds = src.crs

    chip_out = read.read_reproject(
        reader,
        bounds=bounds_read,
        dst_crs=crs_bounds,
        resolution_dst_crs=(abs(expected_transform.a), abs(expected_transform.e)),
    )

    # Skip fully out-of-bounds windows
    if chip_out is None:
        return

    # Check that the output has the correct shape
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == window.height, (
        f"Different height found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    )
    assert named_shape["x"] == window.width, (
        f"Different width found: ({named_shape['y']}, {named_shape['x']}) expected ({window.height}, {window.width})"
    )

    # Verify bounds and transform
    assert chip_out.bounds == bounds_read, f"Different bounds found: {chip_out.bounds} expected: {bounds_read}"
    assert chip_out.transform == expected_transform, (
        f"Different transform found: {chip_out.transform} expected: {expected_transform}"
    )

    # Verify the actual data values match (allowing for small differences due to reprojection)
    assert np.allclose(chip_out_expected, chip_out.values), "Content of the array is different"


RESOLUTION_TEST = (5.0, 5.0)  # Test with 5m resolution (half of original 10m)


@pytest.mark.parametrize("window", TEST_WINDOWS)
def test_read_reproject_other_res(reader_and_materialize, test_raster_path, window):
    """
    Test reprojecting data to a different resolution.

    Verifies read_reproject correctly handles resolution changes:
    10m → 5m should yield 2x the pixels in each dimension. Runs
    against both reader backends via ``reader_and_materialize`` —
    async readers via the pre-load pattern (see
    :func:`_as_geotensor_for_reproject`).
    """
    reader, materialize = reader_and_materialize
    reader = _as_geotensor_for_reproject(reader, materialize)

    with rasterio.open(test_raster_path) as src:
        expected_transform = rasterio.windows.transform(window, src.transform)
        bounds_read = rasterio.windows.bounds(window, src.transform)
        factor_diff_shape = np.array(src.res) / np.array(RESOLUTION_TEST)
        crs_bounds = src.crs

    chip_out = read.read_reproject(reader, bounds=bounds_read, dst_crs=crs_bounds, resolution_dst_crs=RESOLUTION_TEST)

    # Skip fully out-of-bounds windows
    if chip_out is None:
        return

    # Check that the output has the correct shape (scaled by resolution factor)
    named_shape = dict(zip(chip_out.dims, chip_out.shape))
    assert named_shape["y"] == int(window.height * factor_diff_shape[1]), (
        f"Different height found: {named_shape['y']} expected {int(window.height * factor_diff_shape[1])}"
    )
    assert named_shape["x"] == int(window.width * factor_diff_shape[0]), (
        f"Different width found: {named_shape['x']} expected {int(window.width * factor_diff_shape[0])}"
    )

    # Verify bounds remain the same
    assert chip_out.bounds == bounds_read, f"Different bounds found: {chip_out.bounds} expected: {bounds_read}"

    # Verify the transform has the expected resolution
    resolution_signed = (
        math.copysign(RESOLUTION_TEST[0], expected_transform.a),
        math.copysign(RESOLUTION_TEST[1], expected_transform.e),
    )

    expected_transform_new_res = rasterio.Affine.translation(
        expected_transform.c, expected_transform.f
    ) * rasterio.Affine.scale(*resolution_signed)

    assert chip_out.transform == expected_transform_new_res, (
        f"Different transform found: {chip_out.transform} expected: {expected_transform_new_res}"
    )


@pytest.fixture(params=["sync", "async"])
def reader_pair_and_materialize(request, test_raster_path):
    """Yield ``(reader_full, reader_focused, materialize)`` for both backends.

    ``reader_full`` has no pre-set ``window_focus``; ``reader_focused`` is
    constructed with a ``window_focus=Window(50, 50, 100, 100)``.
    Used by :func:`test_read_after_set_window`.
    """
    focus = rasterio.windows.Window(col_off=50, row_off=50, width=100, height=100)

    if request.param == "sync":
        full = rasterio_reader.RasterioReader(test_raster_path)
        focused = rasterio_reader.RasterioReader(test_raster_path, window_focus=focus)
        yield full, focused, _materialize_sync
        return

    pytest.importorskip("async_geotiff")
    obstore = pytest.importorskip("obstore")
    from georeader.async_geotiff_reader import AsyncGeoTIFFReader

    store = obstore.store.LocalStore(prefix=os.path.dirname(test_raster_path))
    fname = os.path.basename(test_raster_path)
    full = asyncio.run(AsyncGeoTIFFReader.open(fname, store=store))
    focused = asyncio.run(AsyncGeoTIFFReader.open(fname, store=store))
    focused.window_focus = focus
    yield full, focused, _materialize_async


def test_read_after_set_window(reader_pair_and_materialize, test_raster_path):
    """
    Test that reading from bounds works correctly with and without a window_focus set.

    Verifies that read_from_bounds produces the same results regardless
    of whether a ``window_focus`` was set on the reader before the call.
    Runs against both reader backends to confirm the windowed-view
    pattern is consistent between :class:`RasterioReader` and
    :class:`AsyncGeoTIFFReader`.
    """
    full_reader, focused_reader, materialize = reader_pair_and_materialize

    # Get bounds within the window_focus area using the raster's CRS
    with rasterio.open(test_raster_path) as src:
        inner_window = rasterio.windows.Window(col_off=75, row_off=75, width=50, height=50)
        bounds_read = rasterio.windows.bounds(inner_window, src.transform)
        crs_bounds = src.crs

    data1 = materialize(read.read_from_bounds(full_reader, bounds_read, crs_bounds=crs_bounds))
    data2 = materialize(read.read_from_bounds(focused_reader, bounds_read, crs_bounds=crs_bounds))

    assert data1.bounds == data2.bounds, f"Different bounds found: {data1.bounds} expected: {data2.bounds}"
    assert data1.transform == data2.transform, (
        f"Different transform found: {data1.transform} expected: {data2.transform}"
    )

    assert np.allclose(data1.values, data2.values), "Content of the array is different"


# =============================================================================
# Tests for dataarray conversion functions
# =============================================================================


class TestDataArrayConversions:
    """Tests for toDataArray and fromDataArray conversion functions."""

    def test_to_dataarray(self, test_raster_path):
        """Test converting GeoTensor to xarray DataArray."""
        rst = rasterio_reader.RasterioReader(test_raster_path)
        geotensor = rst.load()

        da = dataarray.toDataArray(geotensor)

        assert da is not None
        assert da.shape == geotensor.shape
        # Should have x and y coordinates
        assert "x" in da.coords
        assert "y" in da.coords

    def test_from_dataarray_roundtrip(self, test_raster_path):
        """Test roundtrip conversion GeoTensor -> DataArray -> GeoTensor."""
        rst = rasterio_reader.RasterioReader(test_raster_path)
        original = rst.load()

        # Convert to DataArray
        da = dataarray.toDataArray(original)

        # Convert back to GeoTensor
        restored = dataarray.fromDataArray(da, crs=original.crs)

        assert np.allclose(original.values, restored.values)
        assert original.transform.almost_equals(restored.transform, precision=1e-6)

    def test_coords_to_transform_regular_grid(self):
        """Test coords_to_transform with regular grid."""
        import xarray as xr

        # Create regular grid coordinates
        x_coords = np.linspace(0, 100, 101)  # 101 points, 1.0 spacing
        y_coords = np.linspace(100, 0, 101)  # 101 points, -1.0 spacing (top to bottom)

        coords = xr.Coordinates({"x": x_coords, "y": y_coords})

        transform = dataarray.coords_to_transform(coords)

        assert transform is not None
        # Check resolution
        assert abs(transform.a) == pytest.approx(1.0, rel=0.01)
        assert abs(transform.e) == pytest.approx(1.0, rel=0.01)

    def test_getcoords_from_transform_shape(self):
        """Test generating coordinates from transform and shape."""
        from rasterio.transform import from_origin

        transform = from_origin(0, 100, 10, 10)  # 10m resolution
        shape = (50, 50)  # 50 rows, 50 cols

        coords = dataarray.getcoords_from_transform_shape(transform, shape)

        assert "x" in coords
        assert "y" in coords
        assert len(coords["x"]) == 50
        assert len(coords["y"]) == 50

    def test_to_dataarray_with_extra_coords(self, test_raster_path):
        """Test toDataArray with extra coordinates."""
        rst = rasterio_reader.RasterioReader(test_raster_path)
        geotensor = rst.load()

        # Add extra band coordinates
        band_names = [f"band_{i}" for i in range(geotensor.count)]
        extra_coords = {"band": band_names}

        da = dataarray.toDataArray(geotensor, extra_coords=extra_coords)

        assert "band" in da.coords
        assert list(da.coords["band"].values) == band_names

    def test_from_dataarray_with_fill_value(self, test_raster_path):
        """Test fromDataArray with custom fill value."""
        rst = rasterio_reader.RasterioReader(test_raster_path)
        original = rst.load()

        da = dataarray.toDataArray(original)

        restored = dataarray.fromDataArray(da, crs=original.crs, fill_value_default=-9999)

        assert restored.fill_value_default == -9999
